// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWAlOswNazhmxJv7gdwppvvKsm6NFRkE0',
    appId: '1:528913397244:web:da53a75260252505efae79',
    messagingSenderId: '528913397244',
    projectId: 'learn-firebase-girls',
    authDomain: 'learn-firebase-girls.firebaseapp.com',
    storageBucket: 'learn-firebase-girls.appspot.com',
    measurementId: 'G-R3JH0CQ03W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfjj4cqoY-jEB76caZ79s6ww7K8BFNe0',
    appId: '1:528913397244:android:60d496b18f79f1e0efae79',
    messagingSenderId: '528913397244',
    projectId: 'learn-firebase-girls',
    storageBucket: 'learn-firebase-girls.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCycF7uQpktOkCchGPUdm2EdDn_K9rbAgY',
    appId: '1:528913397244:ios:b84f90511530b15befae79',
    messagingSenderId: '528913397244',
    projectId: 'learn-firebase-girls',
    storageBucket: 'learn-firebase-girls.appspot.com',
    iosBundleId: 'com.edugaon.learnFirebase',
  );
}
